# -*- coding: utf-8 -*-
"""loader.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1wj06ixW1q_sWnVxgEptP6_v_-yJjc8IU
"""

# Commented out IPython magic to ensure Python compatibility.
# %cd '/content/drive/My Drive/Spaceapps-2020/Model'
import numpy as np
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras.models import load_model
from preprocess import X,coords
def demonstrate():
  model = load_model('spacia.h5')
  return model.predict(x=X, verbose = 0)

y = demonstrate()
y*=100

import pandas as pd
LatLongLoad = pd.DataFrame(coords,columns=['Lat','Long'])
LatLongLoad['Fire'] = y
LatLongLoad.to_csv("LatLongLoad.csv")

